version = 0.1

[default]
[default.global.parameters]
stack_name = "knowledge-hub-web"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
resolve_s3 = true
parameter_overrides = []

[default.package.parameters]
resolve_s3 = true

