version = 0.1

[default]
[default.global.parameters]
stack_name = "knowledge-hub-api"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
region = "us-east-1"
resolve_s3 = true
parameter_overrides = [
    "CORSOrigins=http://localhost:5173,http://localhost:4173",
    "JWTSecretKey=change-me-in-production"
]

[default.package.parameters]
resolve_s3 = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

